// signatures.h: byte patterns that find the game addresses Note-by-Note uses (see game.cpp, Scan).
//
// GENERATED by tools/sigmaker.py from a memory dump of the L&P build: don't edit, regenerate with
//   .venv\Scripts\python tools\sigmaker.py > mod\nbn\signatures.h
// "??" = a byte that changes between game builds or load addresses (absolute addresses, call/jump
// targets). Func: the match is the function itself. Ref: the match is code that uses the address;
// the address is read from the match at `capture`. Several patterns for one name must agree.
#pragma once

namespace nbn::game::sig {

enum class Kind { Func, Ref };

struct Signature {
    const char* name;
    Kind kind;
    int capture;          // Ref: offset in the match of the 4-byte absolute address
    const char* pattern;  // hex bytes, "??" = any
};

// From mod/build/Release/run/Rocksmith2014_mem.bin (L&P build, dump base 0x009B0000).
inline constexpr Signature kSignatures[] = {
    {"Root", Kind::Ref, 2, "8B 0D ?? ?? ?? ?? 8B 71 18 8D 54 24 0C 52"},  // site rva 0x005ECE
    {"Root", Kind::Ref, 2, "8B 0D ?? ?? ?? ?? 8B 49 28 81 C1 8C 00 00 00 8D 75 C8"},  // site rva 0x005CC9
    {"Root", Kind::Ref, 2, "8B 0D ?? ?? ?? ?? 8B 41 28 8D 4C 24 34 05 8C 00 00 00"},  // site rva 0x005E78
    {"PreviewName", Kind::Ref, 2, "89 35 ?? ?? ?? ?? D9 56 48 C7 46 08 5D 07 00 00"},  // site rva 0x007BF2
    {"PreviewName", Kind::Ref, 2, "89 1D ?? ?? ?? ?? FF 15 ?? ?? ?? ?? 8D 86 8C 00 00 00"},  // site rva 0x007CCC
    {"PreviewName", Kind::Ref, 1, "3D ?? ?? ?? ?? 8D B7 DC 00 00 00 56 FF 15 ?? ?? ?? ??"},  // site rva 0x0098B3
    {"ProviderVtable", Kind::Ref, 2, "C7 06 ?? ?? ?? ?? 89 5E 14 89 5E 18 66 89 5E 1C"},  // site rva 0x04B72B
    {"ProviderVtable", Kind::Ref, 2, "C7 06 ?? ?? ?? ?? 8B 4E 10 85 C9 74 25 8B 15 ?? ?? ?? ?? 85 D2 74 05 E8 ?? ?? ?? ?? 8B 4E 10 85 C9 74 08 8B 01 8B 10 6A 01 FF D2 C7 46 10 00 00 00 00 8D 46 3C"},  // site rva 0x04BA13
    {"PostEventChar", Kind::Func, 0, "55 8B EC 83 EC 10 53 56 57 8B 7D 1C 33 F6 3B FE 74 2B 8B 45 20 50 57 89 75 F0 89 75 F4 89 75 F8 E8 ?? ?? ?? ?? 8B D8 83 C4 08 89 5D FC 85 DB 75 07 5F 5E 5B 8B E5 5D C3 8D 75 F0 EB 03 8B 5D FC 8B 4D 08 51 E8 ?? ?? ?? ?? 8B 55 24 8B 4D 18 52 8B 55 14 56 51 8B 4D 10 52 8B 55 0C 51 52 50 E8 ?? ?? ?? ?? 8B F0 83 C4 20 85 F6 75 0B 85 FF 74 07 8B CB E8 ?? ?? ?? ?? 5F 8B C6 5E 5B 8B E5 5D C3 CC CC CC CC CC CC CC CC CC CC CC CC CC CC CC 55 8B EC 83 EC 38"},
    {"ExecuteActionOnEventId", Kind::Func, 0, "55 8B EC 83 EC 38 B8 20 00 00 00 66 89 45 CA"},
    {"GetEventIDFromPlayingID", Kind::Func, 0, "55 8B EC 8B 0D ?? ?? ?? ?? 85 C9 74 0B 8B 45 08 50 E8 ?? ?? ?? ?? 5D C3 33 C0"},
};

}  // namespace nbn::game::sig
